### ISSUE TITLE
Popup bobler virker ikke (hver gang) i IE 9-11

### ISSUE THREAD

**Issue by KarenFrederiksen** [os2geo/RapportFraStedetMiniMap#3]
Det er ikke altid popup boblerne virker i Internet Explorer 9-11.

**Comment by kjoller** [comment]
@KarenFrederiksen, har du et link til en løsning der giver vanskeligheder?

**Comment by KarenFrederiksen** [comment]
Yes: http://geo.os2geo.dk/couchdb/app-d2121ee08caf832b73a160f9ea022ad9/_design/app2/web/index2.html#/organizations/55c8f9b4fe9c3211e83084cb43002ef2/1d7c600434231dfda57314141c6cdb55/menu 
Du skulle være oprettet som bruger på løsningen, så du nu kan teste. Vær opmærksom på det er en løsning i drift, så ikke noget med at rettet status.

**Comment by kjoller** [comment]
Jeg har testet og oplever det samme.  Jeg tænker at det er relateret til at menuen ikke virker. Jeg får denne fejl i konsollen:

http://geo.os2geo.dk/couchdb/app-d2121ee08caf832b73a160f9ea022ad9/_design/app2/web/index2.html#/organizations/55c8f9b4fe9c3211e83084cb43002ef2/1d7c600434231dfda57314141c6cdb55/menu

Jeg tænker ikke at det nødvendigvis har noget med noget at gøre, men det kan godt være at fejlen blokerer noget andet. @runetvillum ?

**Comment by runetvilum** [comment]
skal løses i os2geo/RapportFraStedetMiniMap#9
